const demo = [
  {
    title: 'Default project',
    dueDate: '2021-12-31',
    priority: 1,
    isComplete: false,
    isDeleted: false,
    notes: '',
    isDemo: true,
    isProject: true,
    parent: null,
    taskID: 0,
  },
  {
    title: 'Wash the dishes',
    parent: 0,
    dueDate: '2021-12-30',
    priority: 2,
    isComplete: false,
    isDeleted: false,
    notes: 'I hate dishes',
    isDemo: true,
    isProject: false,
    taskID: 1,
  },
  {
    title: 'Cook dinner',
    parent: 0,
    dueDate: '2021-12-31',
    priority: 1,
    isComplete: false,
    isDeleted: false,
    notes: 'I love cooking',
    isDemo: true,
    isProject: false,
    taskID: 2,
  },
  {
    title: 'Clean the house',
    dueDate: '2021-12-31',
    priority: 1,
    isComplete: false,
    isDeleted: false,
    notes: 'Yawn',
    isDemo: true,
    isProject: true,
    taskID: 3,
    parent: null,
  },
  {
    title: 'Clean the windows',
    dueDate: '2021-12-31',
    priority: 1,
    isComplete: false,
    isDeleted: false,
    notes: 'omg',
    isDemo: true,
    isProject: false,
    taskID: 4,
    parent: 3,
  },
];

export default demo;
