const displayObject = {
  header: {
    name: 'header',
    nodeType: 'header',
    parent: '#content',
  },
  pageTitle: {
    name: 'pageTitle',
    nodeType: 'h1',
    parent: 'header',
    text: 'To-Do List',
  },
  newTaskButtonDiv: {
    name: 'new-task-button-div',
    nodeType: 'div',
    parent: 'header',
    class1: 'new-task-button-div',
  },
  newTaskButton: {
    name: 'newTaskButton',
    nodeType: 'input',
    parent: '.new-task-button-div',
    inputType: 'button',
    value: 'New Task',
    objID: 'new-task',
  },
  newProjectButton: {
    name: 'newProjectButton',
    nodeType: 'input',
    parent: '.new-task-button-div',
    inputType: 'button',
    value: 'New Project',
    objID: 'new-project',
  },
  display: {
    name: 'display',
    nodeType: 'div',
    parent: '#content',
    class1: 'display',
  },
  projectCard: {
    name: 'projectCard',
    nodeType: 'div',
    parent: '.display',
    class1: 'task-card',
    class2: 'project-card',
  },
  taskCard: {
    name: 'taskCard',
    nodeType: 'div',
    class1: 'task-card',
  },
  titleDiv: {
    name: 'title-div',
    nodeType: 'div',
    class1: 'title-div',
  },
  taskAttributes: {
    name: 'attributes',
    nodeType: 'div',
    class1: 'attributes',
  },
  taskTitle: {
    name: 'taskTitle',
    nodeType: 'input',
    inputType: 'text',
    class1: 'task-title',
    placeholder: 'Please enter a title for this task',
  },
  dueDate: {
    name: 'dueDate',
    nodeType: 'input',
    inputType: 'date',
    class1: 'due-date',
  },
  prioritySelect: {
    name: 'prioritySelect',
    nodeType: 'select',
    class1: 'priority-select',
    innerHTML: '<option value="0">Low</option><option value="1">Normal</option><option value="2">Urgent</option>',
  },
  projectSelect: {
    name: 'projectSelect',
    nodeType: 'select',
    class1: 'project-select',
  },
  notes: {
    name: 'notes',
    nodeType: 'input',
    inputType: 'text',
    class1: 'notes',
    placeholder: 'Please enter any notes about this task',
  },
  innerDisplay: {
    name: 'innerDisplay',
    nodeType: 'div',
    class1: 'inner-display',
  },
  newTaskForm: {
    name: 'newTaskForm',
    nodeType: 'fieldset',
    class1: 'new-task-form',
    parent: '.display',
  },
  submitButton: {
    name: 'submitButton',
    nodeType: 'input',
    inputType: 'button',
    class1: 'submit',
    parent: '.new-task-form',
    value: 'Submit',
  },
};

const demo = {
  demoProject1: {
    title: 'A demo project',
    dueDate: '2021-12-31',
    priority: 1,
    notes: 'This is a test project',
    type: 'project',
    project: 1,
    numberTasks: 0,
    taskList: [],
    isProject: true,
  },
  demoProject2: {
    title: 'A second demo project',
    dueDate: '2022-01-15',
    priority: 1,
    notes: 'This is another test project',
    type: 'project',
    project: 2,
    numberTasks: 0,
    taskList: [],
    isProject: true,
  },
  demoProject3: {
    title: 'A third demo project',
    dueDate: '2022-02-01',
    priority: 1,
    notes: 'This is another test project',
    type: 'project',
    project: 3,
    numberTasks: 0,
    taskList: [],
    isProject: true,
  },
  demoTask1: {
    title: 'Wash the dishes',
    dueDate: '2021-12-30',
    priority: 2,
    notes: 'I hate dishes',
    type: 'task',
    isProject: false,
    project: 0,
  },
  demoTask2: {
    title: 'Cook dinner',
    dueDate: '2021-12-31',
    priority: 1,
    notes: 'Yum',
    type: 'task',
    isProject: false,
    project: 0,
  },
  demoTask3: {
    title: 'Go shopping',
    dueDate: '2022-01-02',
    priority: 1,
    notes: 'Need food',
    type: 'task',
    isProject: false,
    project: 1,
  },
  demoTask4: {
    title: 'Play with dog',
    dueDate: '2022-01-03',
    priority: 2,
    notes: 'Dogs are great',
    type: 'task',
    isProject: false,
    project: 1,
  },
  demoTask5: {
    title: 'Go shopping',
    dueDate: '2022-01-04',
    priority: 1,
    notes: 'Need food',
    type: 'task',
    isProject: false,
    project: 2,
  },
  demoTask6: {
    title: 'Play with dog 2',
    dueDate: '2022-01-05',
    priority: 2,
    notes: 'Dogs are great',
    type: 'task',
    isProject: false,
    project: 2,
  },
  demoTask7: {
    title: 'test this stupid program',
    dueDate: '2022-10-18',
    priority: 2,
    notes: 'this is annoying',
    type: 'task',
    isProject: false,
    project: 2,
  }
};

const emptyTask = {
  title: '',
  dueDate: '',
  priority: '1',
  notes: '',
  type: '',
  taskList: [],
  completed: false,
};

export { displayObject, demo, emptyTask };
