const displayObject = {
  header: {
    name: 'header',
    nodeType: 'header',
    parent: '#content',
  },
  pageTitle: {
    name: 'pageTitle',
    nodeType: 'h1',
    parent: 'header',
    text: 'To-Do List',
  },
  newTaskButtonDiv: {
    name: 'new-task-button-div',
    nodeType: 'div',
    parent: 'header',
    class1: 'new-task-button-div',
  },
  newTaskButton: {
    name: 'newTaskButton',
    nodeType: 'input',
    parent: '.new-task-button-div',
    inputType: 'button',
    value: 'New Task',
    objID: 'new-task',
  },
  newProjectButton: {
    name: 'newProjectButton',
    nodeType: 'input',
    parent: '.new-task-button-div',
    inputType: 'button',
    value: 'New Project',
    objID: 'new-project',
  },
  display: {
    name: 'display',
    nodeType: 'div',
    parent: '#content',
    class1: 'display',
  },
  projectCard: {
    name: 'projectCard',
    nodeType: 'div',
    parent: '.display',
    class1: 'task-card',
    class2: 'project-card',
  },
  taskCard: {
    name: 'taskCard',
    nodeType: 'div',
    class1: 'task-card',
  },
  titleDiv: {
    name: 'title-div',
    nodeType: 'div',
    class1: 'title-div',
  },
  taskAttributes: {
    name: 'attributes',
    nodeType: 'div',
    class1: 'attributes',
  },
  taskTitle: {
    name: 'taskTitle',
    nodeType: 'input',
    inputType: 'text',
    class1: 'task-title',
    placeholder: 'Please enter a title for this task',
  },
  dueDate: {
    name: 'dueDate',
    nodeType: 'input',
    inputType: 'date',
    class1: 'due-date',
  },
  prioritySelect: {
    name: 'prioritySelect',
    nodeType: 'select',
    class1: 'priority-select',
    innerHTML: '<option value="0">Low</option><option value="1">Normal</option><option value="2">Urgent</option>',
  },
  projectSelect: {
    name: 'projectSelect',
    nodeType: 'select',
    class1: 'project-select',
  },
  notes: {
    name: 'notes',
    nodeType: 'textarea',
    class1: 'notes',
    placeholder: 'Please enter any notes about this task',
  },
  innerDisplay: {
    name: 'innerDisplay',
    nodeType: 'div',
    class1: 'inner-display',
  },
  newTaskForm: {
    name: 'newTaskForm',
    nodeType: 'fieldset',
    class1: 'new-task-form',
    parent: '.display',
  },
  submitButton: {
    name: 'submitButton',
    nodeType: 'input',
    inputType: 'button',
    class1: 'submit',
    parent: '.new-task-form',
    value: 'Submit',
  },
  toggleCompleteButton: {
    name: 'toggleCompleteButton',
    nodeType: 'input',
    inputType: 'button',
    class1: 'toggle-complete',
  },
  deleteButton: {
    name: 'deleteButton',
    nodeType: 'input',
    inputType: 'button',
    class1: 'delete-button',
  },
  titleClose: {
    name: 'titleClose',
    nodeType: 'div',
    class1: 'title-close',
  },
};

const demo = {
  demoProject1: {
    title: 'Default project',
    dueDate: '2021-12-31',
    priority: 1,
    notes: '',
    taskList: [],
    isProject: true,
    deleted: false,
    isDemo: true,
  },
  demoTask1: {
    title: 'Wash the dishes',
    dueDate: '2021-12-30',
    priority: 2,
    notes: 'I hate dishes',
    isProject: false,
    deleted: false,
    isDemo: true,
    parentTask: 0,
  },
  demoTask2: {
    title: 'Cook dinner',
    dueDate: '2021-12-31',
    priority: 1,
    notes: 'Yum',
    isProject: false,
    deleted: false,
    isDemo: true,
    parentTask: 0,
  },
};

const emptyTask = {
  title: '',
  dueDate: '',
  priority: 1,
  notes: '',
  type: '',
  taskList: [],
  completed: false,
  deleted: false,
  parent: -1,
};

export { displayObject, demo, emptyTask };
